### ISSUE TITLE
the pretrained model of deepglobe

### ISSUE THREAD

**Issue by cedricgsh** [liqiokkk/FCtL#2]
Thank you for open source this great job. It really inspired me a lot.
I try to use the pretained model in your repo to inference the deepglobe dataset.
The error shows that the pretrained model dose not belong to the deepglobe dataset.
May be I miss some important details, or you have not upload the pretrained model of the deepglobe dataset.
I will appreciate you if you could help me. @liqiokkk 
![微信图片_20211021225052](https://user-images.githubusercontent.com/33807572/138303011-f351481f-b0d9-4393-9f0b-d2d89e40076f.png)

**Comment by liqiokkk** [comment]
Thank you for your interest. 
We only upload code and pretrained model about Inria Aerial dataset currently, the code needs a little modification if you use the code in DeepGlobe, because we use the global context in DeepGlobe.
We will upload code and pretrained model about DeepGlobe dataset later.

**Comment by cedricgsh** [comment]
Sorry to bother you again.
I try to using your code to train a model on deepglobe.
However, for every training stage, it will cost two days at least.
It was too long, therefore, could offer your pretrained model as soon as possible.
I really need that. 
I will appreciate you if you could help me. @liqiokkk

**Comment by liqiokkk** [comment]
We uploaded the code and pre-trained model about Deepglobe dataset in the Deepglobe branch.

**Comment by cedricgsh** [comment]
Thank you very much!

**Comment by kangqiang-kq** [comment]
> 非常感谢！

时间有点久远了。但还是想询问您一个问题。请问您是否遇到这个问题，运行deepglobe ，train_medium.sh时候。 

<img width="1068" alt="image" src="https://github.com/liqiokkk/FCtL/assets/74480453/532e5eea-92be-431d-8f3e-693ca0617454">
<img width="760" alt="image" src="https://github.com/liqiokkk/FCtL/assets/74480453/8169c91b-1f7d-4ed1-bd93-3f5cc94872cb">
