### ISSUE TITLE
Should loss.backward() set "retain_graph=True" in the training process.

### ISSUE THREAD

**Issue by zyxu1996** [liqiokkk/FCtL#3]
As to my understand, an image will contain many patches, but it seems that you only backward the loss for once.  
The code in helper.py is as follows.
`
loss = self.criterion(output_patches, label_patches_var)
loss.backward()#retain_graph=True)
`

**Comment by liqiokkk** [comment]
We use gradient accumulation.
According to my understanding, we just empty the gradient after processing many patches.
We learn the code from GLNet (mode=2).

**Comment by kangqiang-kq** [comment]
Traceback (most recent call last):
  File "train_deep_globe.py", line 111, in <module>
    loss = trainer.train(sample_batched, model, c_fixed, global_fixed) # sample
  File "/home/kangqiang/PycharmProjects/FCtl_Deepglobe/helper.py", line 282, in train
    loss = self.criterion(output_patches, label_patches_var)
  File "train_deep_globe.py", line 92, in <lambda>
    criterion = lambda x,y: criterion1(x, y)
~~~
RuntimeError: The size of tensor a (1548384) must match the size of tensor b (4645152) at non-singleton dimension 0
您好！@zyxu1996 请问您是否遇到此问题，运行 bash pre.sh  时
