### ISSUE TITLE
Can you tell me the method you use to transform the .tif to .png?

### ISSUE THREAD

**Issue by Liuyangfeixiao** [liqiokkk/FCtL#5]
I used cv2 to transform the .tif to .png, but the num of label channels is 3, not 2, which lead to the mismatch of the out_patch and the label_patch

**Comment by liqiokkk** [comment]
Sorry, I do not understand your issue, could you describe it more clearly?

**Comment by Liuyangfeixiao** [comment]
The images in Inria Aerial dataset are all tif format, while the image format in data_1/..../Label is png. So I used cv2 to transform the tif to png. However, It caused error while training, because the out_patches of the model have 2 channels corresponding to the default num_class, but the label_patchs have 3 channels(RGB).&nbsp; Could you please tell me whether you had met the question before and how did you solve it? Thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月14日(星期二) 晚上7:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [liqiokkk/FCtL] Can you tell me the method you use to transform the .tif to .png? (Issue #5)





 
Sorry, I do not understand your issue, could you describe it more clearly?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
